[package]
authors = ["Michael Daffin <michael@daffin.io>"]
name = "scribe"
version = "0.1.0"

[dependencies]
failure = "0.1.1"
failure_derive = "0.1.1"
structopt = "0.2.8"
human-panic = "0.4.0"
termion = "1.5.1"
log = "0.4.1"
simplelog = "0.5.1"
